// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/dataFrame.proto

package protoSerializer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MESSAGE_DATA_FRAME struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FROM          string                 `protobuf:"bytes,1,opt,name=FROM,proto3" json:"FROM,omitempty"`
	TO            string                 `protobuf:"bytes,2,opt,name=TO,proto3" json:"TO,omitempty"`
	TYPE          string                 `protobuf:"bytes,3,opt,name=TYPE,proto3" json:"TYPE,omitempty"`
	ADD_ON        string                 `protobuf:"bytes,4,opt,name=ADD_ON,json=ADDON,proto3" json:"ADD_ON,omitempty"`
	ID            int64                  `protobuf:"varint,5,opt,name=ID,proto3" json:"ID,omitempty"`
	TS            int64                  `protobuf:"varint,6,opt,name=TS,proto3" json:"TS,omitempty"`
	DATA          string                 `protobuf:"bytes,7,opt,name=DATA,proto3" json:"DATA,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MESSAGE_DATA_FRAME) Reset() {
	*x = MESSAGE_DATA_FRAME{}
	mi := &file_proto_dataFrame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MESSAGE_DATA_FRAME) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MESSAGE_DATA_FRAME) ProtoMessage() {}

func (x *MESSAGE_DATA_FRAME) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataFrame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MESSAGE_DATA_FRAME.ProtoReflect.Descriptor instead.
func (*MESSAGE_DATA_FRAME) Descriptor() ([]byte, []int) {
	return file_proto_dataFrame_proto_rawDescGZIP(), []int{0}
}

func (x *MESSAGE_DATA_FRAME) GetFROM() string {
	if x != nil {
		return x.FROM
	}
	return ""
}

func (x *MESSAGE_DATA_FRAME) GetTO() string {
	if x != nil {
		return x.TO
	}
	return ""
}

func (x *MESSAGE_DATA_FRAME) GetTYPE() string {
	if x != nil {
		return x.TYPE
	}
	return ""
}

func (x *MESSAGE_DATA_FRAME) GetADD_ON() string {
	if x != nil {
		return x.ADD_ON
	}
	return ""
}

func (x *MESSAGE_DATA_FRAME) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *MESSAGE_DATA_FRAME) GetTS() int64 {
	if x != nil {
		return x.TS
	}
	return 0
}

func (x *MESSAGE_DATA_FRAME) GetDATA() string {
	if x != nil {
		return x.DATA
	}
	return ""
}

var File_proto_dataFrame_proto protoreflect.FileDescriptor

const file_proto_dataFrame_proto_rawDesc = "" +
	"\n" +
	"\x15proto/dataFrame.proto\x12\tdataFrame\"\x97\x01\n" +
	"\x12MESSAGE_DATA_FRAME\x12\x12\n" +
	"\x04FROM\x18\x01 \x01(\tR\x04FROM\x12\x0e\n" +
	"\x02TO\x18\x02 \x01(\tR\x02TO\x12\x12\n" +
	"\x04TYPE\x18\x03 \x01(\tR\x04TYPE\x12\x15\n" +
	"\x06ADD_ON\x18\x04 \x01(\tR\x05ADDON\x12\x0e\n" +
	"\x02ID\x18\x05 \x01(\x03R\x02ID\x12\x0e\n" +
	"\x02TS\x18\x06 \x01(\x03R\x02TS\x12\x12\n" +
	"\x04DATA\x18\a \x01(\tR\x04DATAB\x19Z\x17./proto;protoSerializerb\x06proto3"

var (
	file_proto_dataFrame_proto_rawDescOnce sync.Once
	file_proto_dataFrame_proto_rawDescData []byte
)

func file_proto_dataFrame_proto_rawDescGZIP() []byte {
	file_proto_dataFrame_proto_rawDescOnce.Do(func() {
		file_proto_dataFrame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dataFrame_proto_rawDesc), len(file_proto_dataFrame_proto_rawDesc)))
	})
	return file_proto_dataFrame_proto_rawDescData
}

var file_proto_dataFrame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_dataFrame_proto_goTypes = []any{
	(*MESSAGE_DATA_FRAME)(nil), // 0: dataFrame.MESSAGE_DATA_FRAME
}
var file_proto_dataFrame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dataFrame_proto_init() }
func file_proto_dataFrame_proto_init() {
	if File_proto_dataFrame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dataFrame_proto_rawDesc), len(file_proto_dataFrame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dataFrame_proto_goTypes,
		DependencyIndexes: file_proto_dataFrame_proto_depIdxs,
		MessageInfos:      file_proto_dataFrame_proto_msgTypes,
	}.Build()
	File_proto_dataFrame_proto = out.File
	file_proto_dataFrame_proto_goTypes = nil
	file_proto_dataFrame_proto_depIdxs = nil
}
