// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: Seralize/prtobuf/dataFrame.proto

package protoSerializer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BASE_FRAME struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	XId           int32                  `protobuf:"varint,2,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	XV            int32                  `protobuf:"varint,3,opt,name=_v,json=V,proto3" json:"_v,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	From          string                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	Data          string                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BASE_FRAME) Reset() {
	*x = BASE_FRAME{}
	mi := &file_Seralize_prtobuf_dataFrame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BASE_FRAME) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BASE_FRAME) ProtoMessage() {}

func (x *BASE_FRAME) ProtoReflect() protoreflect.Message {
	mi := &file_Seralize_prtobuf_dataFrame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BASE_FRAME.ProtoReflect.Descriptor instead.
func (*BASE_FRAME) Descriptor() ([]byte, []int) {
	return file_Seralize_prtobuf_dataFrame_proto_rawDescGZIP(), []int{0}
}

func (x *BASE_FRAME) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BASE_FRAME) GetXId() int32 {
	if x != nil {
		return x.XId
	}
	return 0
}

func (x *BASE_FRAME) GetXV() int32 {
	if x != nil {
		return x.XV
	}
	return 0
}

func (x *BASE_FRAME) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BASE_FRAME) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *BASE_FRAME) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *BASE_FRAME) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_Seralize_prtobuf_dataFrame_proto protoreflect.FileDescriptor

const file_Seralize_prtobuf_dataFrame_proto_rawDesc = "" +
	"\n" +
	" Seralize/prtobuf/dataFrame.proto\x12\tdataFrame\"\x8c\x01\n" +
	"\n" +
	"BASE_FRAME\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x0f\n" +
	"\x03_id\x18\x02 \x01(\x05R\x02Id\x12\r\n" +
	"\x02_v\x18\x03 \x01(\x05R\x01V\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\x12\x12\n" +
	"\x04from\x18\x05 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\tR\x02to\x12\x12\n" +
	"\x04data\x18\a \x01(\tR\x04dataB\x1cZ\x1a./protobuf;protoSerializerb\x06proto3"

var (
	file_Seralize_prtobuf_dataFrame_proto_rawDescOnce sync.Once
	file_Seralize_prtobuf_dataFrame_proto_rawDescData []byte
)

func file_Seralize_prtobuf_dataFrame_proto_rawDescGZIP() []byte {
	file_Seralize_prtobuf_dataFrame_proto_rawDescOnce.Do(func() {
		file_Seralize_prtobuf_dataFrame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Seralize_prtobuf_dataFrame_proto_rawDesc), len(file_Seralize_prtobuf_dataFrame_proto_rawDesc)))
	})
	return file_Seralize_prtobuf_dataFrame_proto_rawDescData
}

var file_Seralize_prtobuf_dataFrame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Seralize_prtobuf_dataFrame_proto_goTypes = []any{
	(*BASE_FRAME)(nil), // 0: dataFrame.BASE_FRAME
}
var file_Seralize_prtobuf_dataFrame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Seralize_prtobuf_dataFrame_proto_init() }
func file_Seralize_prtobuf_dataFrame_proto_init() {
	if File_Seralize_prtobuf_dataFrame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Seralize_prtobuf_dataFrame_proto_rawDesc), len(file_Seralize_prtobuf_dataFrame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Seralize_prtobuf_dataFrame_proto_goTypes,
		DependencyIndexes: file_Seralize_prtobuf_dataFrame_proto_depIdxs,
		MessageInfos:      file_Seralize_prtobuf_dataFrame_proto_msgTypes,
	}.Build()
	File_Seralize_prtobuf_dataFrame_proto = out.File
	file_Seralize_prtobuf_dataFrame_proto_goTypes = nil
	file_Seralize_prtobuf_dataFrame_proto_depIdxs = nil
}
